### PR TITLE
fix bug 2

### PR DESCRIPTION
**Pull request by namuetn**
## Related Tickets:
- [#30507](https://edu-redmine.sun-asterisk.vn/issues/30507)

## Notes Impacted Areas:
- N/A.

## Attachments:
- N/A.

### CODE REVIEW

**Comment by namuetn** [comment]
ready

**Comment by namuetn** [comment]
ready

**Comment by namuetn** [comment]
ready

**Comment by namuetn** [comment]
ready

**Review by huyenttm-0901 — COMMENTED** [review]
conflict

**Comment by namuetn** [comment]
ready

**Pull request merged**
